apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicate-backend
  namespace: medicate 
  labels:
    app: medicate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicate-backend
  template:
    metadata:
      labels:
        app: medicate-backend
    spec:
      containers:
      - name: medicate-backend
        image: major7/medicate-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "384Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
        env:
        - name: REDIS_HOST
          value: "redis.medicate.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: medicate-backend
  namespace: medicate
spec:
  selector:
    app: medicate-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medicate-backend
  namespace: medicate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: medicate-backend
            port:
              number: 8080 