apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: medicate
  annotations:
    volume.alpha.kubernetes.io/storage-class: ssd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: redis-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: medicate
  labels:
    type: redis-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: /data/redis
