apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: medicate
data:
  redis.conf: |
    databases 16
    maxclients 12000
    timeout 30
    port 6379
    tcp-keepalive 300
    logfile ""
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no